version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - db_volume:/home/app/web/app/db
      - static_volume:/home/app/web/app/static
      - media_volume:/home/app/web/app/media
    ports:
      - 8000:8000
    # expose:
    #   - 8000
    env_file:
      - ./.env.prod
    # depends_on:
    #   - db
  # db:
  #   image: postgres:12.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env.prod
  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - static_volume:/home/app/web/app/static
  #     - media_volume:/home/app/web/app/media
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - web

volumes:
  db_volume:
  static_volume:
  media_volume: