# Generated by Django 3.1.5 on 2021-01-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
