# Generated by Django 3.1.5 on 2021-01-13 21:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('concentration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('concentration', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='concentration.concentration')),
            ],
        ),
    ]
