# Generated by Django 3.1.5 on 2021-01-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentration', '0003_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='requirement',
        ),
        migrations.AddField(
            model_name='requirement',
            name='course',
            field=models.ManyToManyField(to='concentration.Course'),
        ),
    ]
