# Generated by Django 3.1.5 on 2021-01-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentration', '0004_auto_20210114_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='concentration',
        ),
        migrations.AddField(
            model_name='concentration',
            name='requirement',
            field=models.ManyToManyField(to='concentration.Requirement'),
        ),
    ]
