# Generated by Django 3.1.5 on 2021-01-14 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concentration', '0005_auto_20210114_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField()),
                ('hide', models.BooleanField()),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concentration.course')),
            ],
        ),
        migrations.AddField(
            model_name='requirement',
            name='condition',
            field=models.ManyToManyField(to='concentration.Condition'),
        ),
    ]
