# Generated by Django 3.1.5 on 2021-01-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentration', '0008_auto_20210115_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='allows_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='max_courses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='min_courses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
