# Generated by Django 3.1.5 on 2021-01-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentration', '0009_auto_20210115_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='condition',
            field=models.ManyToManyField(blank=True, null=True, to='concentration.Condition'),
        ),
    ]
