# Generated by Django 3.1.5 on 2021-01-15 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concentration', '0008_auto_20210115_1441'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='concentration',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='concentration.concentration'),
            preserve_default=False,
        ),
    ]
