# Generated by Django 3.1.5 on 2021-01-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concentration', '0008_auto_20210115_1441'),
        ('plan', '0002_plan_concentration'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('INPROGRESS', 'In progress')], default='INPROGRESS', max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='submission_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='concentration',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='concentration.concentration'),
        ),
        migrations.CreateModel(
            name='PlanRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='plan.plan')),
                ('requirement', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='concentration.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='PlanCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='concentration.course')),
                ('requirement', models.ManyToManyField(related_name='courses', to='concentration.Requirement')),
            ],
        ),
    ]
