# Generated by Django 3.1.5 on 2021-01-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20210115_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plancourse',
            name='requirement',
        ),
        migrations.AddField(
            model_name='planrequirement',
            name='course',
            field=models.ManyToManyField(to='plan.PlanCourse'),
        ),
    ]
