# Generated by Django 3.1.5 on 2021-01-26 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20210115_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planrequirement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_requirements', to='plan.plan'),
        ),
    ]
